### ISSUE TITLE
General Discussion: HB-UW-Sen-THPL

### ISSUE THREAD

**Issue by jp112sdl** [jp112sdl/Beispiel_AskSinPP#1]

**Comment by jp112sdl** [comment]
Hallo [Erwin](https://github.com/erwin23)!
Hab dich mal in dem ersten Beitrag erwähnt. 
Bekommst du darüber eine Benachrichtigung!?

**Comment by erwin23** [comment]
Bei mir könnte ich den Innensensor HB-UW-Sen-THPL-I und den Aussensensor HB-UW-Sen-THPL-O nach dem Einspielen des Addons anlernen. Beide zeigen auch Werte.
Besten Dank und Gruss aus Bremen erwin23

**Comment by McSpitz** [comment]
Hi, habe auch eine eMail. Hoffe es ist ok für euch. Gruß aus Delmenhorst 😊

Von meinem iPad gesendet

**Comment by jp112sdl** [comment]
Hallo ihr zwei :) 

@erwin23 Ich habe es nun auch hinbekommen, das Gerät anzulernen.

Als nächstes werde ich den Code dahingehend umschreiben, dass man einen BH1750 als Lichtsensor nutzen kann. der TSL2561 ist schlecht verfügbar - oder wenn, dann nur für einen relativ hohen Preis.

Mittlerweile habe ich das Originalprojekt geforkt und das RaspberryMatic Addon auch dort abgelegt.
Es ist nun nach der Installation auch unter Zusatzsoftware aufgelistet und kann bei Bedarf auch wieder sauber deinstalliert werden.

Das Addon liegt [hier](https://github.com/jp112sdl/Wettersensor/tree/master/Contrib/CCURM).

Ich würde für Fragen / Diskussionen auch gern noch mal umziehen - [direkt in das entsprechende Repository](https://github.com/jp112sdl/Wettersensor/issues/1).

**Comment by erwin23** [comment]
Hallo,

hast du noch was geändert zur Vorabversion.

Beste Grüsse aus Bremen

 

Gesendet: Dienstag, 13. Februar 2018 um 06:29 Uhr
Von: Jérôme <notifications@github.com>
An: jp112sdl/Beispiel_AskSinPP <Beispiel_AskSinPP@noreply.github.com>
Cc: erwin23 <erwin23@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [jp112sdl/Beispiel_AskSinPP] General Discussion: HB-UW-Sen-THPL (#1)


Hallo ihr zwei :)

@erwin23 Ich habe es nun auch hinbekommen, das Gerät anzulernen.

Als nächstes werde ich den Code dahingehend umschreiben, dass man einen BH1750 als Lichtsensor nutzen kann. der TSL2561 ist schlecht verfügbar - oder wenn, dann nur für einen relativ hohen Preis.

Mittlerweile habe ich das Originalprojekt geforkt und das RaspberryMatic Addon auch dort abgelegt.
Es ist nun nach der Installation auch unter Zusatzsoftware aufgelistet und kann bei Bedarf auch wieder sauber deinstalliert werden.

Das Addon liegt hier.

Ich würde für Fragen / Diskussionen auch gern noch mal umziehen - direkt in das entsprechende Repository.

**Comment by jp112sdl** [comment]
Ja, vieles! 
Hab die Ratschläge von Jens Maus noch umgesetzt und daraus ein "sauberes" Addon gemacht.
Für den Betrieb wird es keine Auswirkungen geben. Wenn es bei dir jetzt läuft, dann kannst du es so lassen und brauchst das Addon nicht noch mal installieren.

Kennst du noch mehr Leute, die auf das RaspberryMatic Addon gewartet haben?

**Comment by erwin23** [comment]
Ja bei meinem Nachbarn habe ich es auch eingespielt.

Sind beide von LXCCU auf Raspberrymatic umgezogen.

Hatte vorher bei mir schon die Dateien händisch geändert und  die WWW Dateien rübercopiert.

Lief auch, nur umständlich und nicht zu vermitteln. Hatte mir schon eine kleines Script

geschrieben um die Dateien webui.js und DEVDB.tcl von /tmp aus zu ändern.

Natürlich nicht die Liga wie ein Addon.

Beste Grüsse aus Bremen

 

Gesendet: Dienstag, 13. Februar 2018 um 12:26 Uhr
Von: Jérôme <notifications@github.com>
An: jp112sdl/Beispiel_AskSinPP <Beispiel_AskSinPP@noreply.github.com>
Cc: erwin23 <erwin23@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [jp112sdl/Beispiel_AskSinPP] General Discussion: HB-UW-Sen-THPL (#1)


Ja, vieles!
Hab die Ratschläge von Jens Maus noch umgesetzt und daraus ein "sauberes" Addon gemacht.
Für den Betrieb wird es keine Auswirkungen geben. Wenn es bei dir jetzt läuft, dann kannst du es so lassen und brauchst das Addon nicht noch mal installieren.

Kennst du noch mehr Leute, die auf das RaspberryMatic Addon gewartet haben?

**Comment by erwin23** [comment]
Hallo,

hatte noch Anfragen auf mein Post in dem  Beitrag


https://homematic-forum.de/forum/viewtopic.php?f=65&t=37723&p=417940#p417940 bekommen.

Wäre nett wenn du den Github Link dort postet.

Eventuell auch mit J.Maus kommunizierts, damit das Addon auch in seiner Liste aufgenommen wird.

Beste Grüsse aus Bremen

 


Gesendet: Dienstag, 13. Februar 2018 um 12:26 Uhr
Von: Jérôme <notifications@github.com>
An: jp112sdl/Beispiel_AskSinPP <Beispiel_AskSinPP@noreply.github.com>
Cc: erwin23 <erwin23@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [jp112sdl/Beispiel_AskSinPP] General Discussion: HB-UW-Sen-THPL (#1)


Ja, vieles!
Hab die Ratschläge von Jens Maus noch umgesetzt und daraus ein "sauberes" Addon gemacht.
Für den Betrieb wird es keine Auswirkungen geben. Wenn es bei dir jetzt läuft, dann kannst du es so lassen und brauchst das Addon nicht noch mal installieren.

Kennst du noch mehr Leute, die auf das RaspberryMatic Addon gewartet haben?
