### ISSUE TITLE
Example uses HM-RC-P1 as sketch with duoled, but picture only shows single led

### ISSUE THREAD

**Issue by harvey637** [jp112sdl/Beispiel_AskSinPP#12]
Hi,

the sketch for the single button example uses HM-RC-P1.ino, which has a duoled on pin 4 and 5.
The picture explaining the example only uses single led on pin4.
You only see half the colors :-)

this only as remainder.

cu
Harvey

**Comment by jp112sdl** [comment]
bf56162
