### ISSUE TITLE
battery info missing in webgui for battery-version of SenAct-4-4

### ISSUE THREAD

**Issue by harvey637** [jp112sdl/Beispiel_AskSinPP#14]
Hi,
even if powerusage of the battery variants is in hot discussion one more thingy irritates me:
- in List0 (maintenance) I see a field "battery_low = false" (maybe spelling is different, this is only from memory), which is exactly what I expect for a battery device.
- in the Webgui I see four relays and 4 switches/4 contacts, but no "Battery ok" field.
This is only compared to other "official" sensors, which (all) show sensor values AND battery status.
Battery status even with all Sensors on a multi sensor device :-)
Sound to me like something inside the "not so well documented" device.xml.
Also expected is this battery device in the "list of batteries", but ther only some original batteries devices are found, a lot of original devices do not show up.

When dealing with device.xml: do you know where I can find the "HMID" (this 3 byte hex serial)
anywhere in gui or else? I only see them when sniffing with cc1101 of some other device?
Not in iobroker, webgui, HQ-webgui ...

**Comment by jp112sdl** [comment]
There is no "extra" field for the battery state.
When battery is low, it causes a "Servicemeldung" in CCU.
You can't see this in the device itself.

> where I can find the "HMID" (this 3 byte hex serial) anywhere in gui or else?

In `/etc/config/rfd/` is a file for each device. There you can find the IDs in it.

I don't know how HQ WebUI works and how it handles custom devices...

**Comment by harvey637** [comment]
Hi,
when using the WDS30-TO2-1820 (no addon device, regular device model 
 {0x00, 0xa8}, // Device Model
every temperature in webgui has a gray field same size right of temperature (so it is like two columns)
which displays the words "Battery ok". As these gui fields are generated by entries inside the
device.xml (in this case the original WDS30-OT2) the fields are displayed == OK.
In case of your Sens-Act-4-4_BAT (yes, the _BAT!) I only see the status of relais and buttons in one
column, the second column with the "Battery ok" is missing. 
Not really a problem, as I assume a warning in the system_messages, when the battery goes low.
Only some optical "difference" to original devices.
I stumbled over this, as I play with SensAct_battery and WDS30_ds18b20 by accident.
cu
Harvey

**Comment by harvey637** [comment]
The question about the "HMID" comes from my fault while playing around, I changes the "Serial", this
10 byte string, that is used everywhere in the gui (like HMJPSENS01).  The first field in 
const struct DeviceInfo PROGMEM devinfo = {
{0x00, 0xa8, 0x01}, // Device ID
is used as address in the rf-packets, I see communication like "0FFFF -> 00A801 06 ......"
This is the DeviceID (sometimes in bootloader named HMID) that is unique to every single device.
And this DeviceID is shown nowhere, only as address inside the cc1101 rf-packets.
I made a mistake, forgot to change, and wanted to know where to find used DeviceIDs.
I will ask this again in homematic-forum, this is no issue!

Thank You
Harvey

**Comment by jp112sdl** [comment]
It's by design.
Don't know, why eq3 has chosen to put the "Battery ok" field to sensors, but not to shutter contacts and other devices.

I won't change the XML files of the HB-UNI-SenAct-4-4 devices. 
It is a mix (nearly whole content copy) of the SW XML and the RC / SC XML.

When battery goes to the low state, a "Servicemeldung" appears and I think thats sufficient. 

Btw.: The HM-WDS30-OT2 uses a dedicated LOWBAT event frame.

If you want to create your own homebrew device, you can choose yourself, what's best.

**Comment by jp112sdl** [comment]
> wanted to know where to find used DeviceIDs

as described in [commented before](
https://github.com/jp112sdl/Beispiel_AskSinPP/issues/14#issuecomment-41431854):

<img width="627" alt="bildschirmfoto 2018-08-20 um 17 10 58" src="https://user-images.githubusercontent.com/18190139/44348966-383a5300-a49c-11e8-8be8-8ecc333309d2.png">

**Comment by harvey637** [comment]
Thank you for your very fast answer!
It is ok with me, I just thougt it is part of the device.xml, that could be "polished" to be like
other battery devices. If it not with contacts, it is perfectly ok!

With the addon "HQ-Webgui" you can easy see a lot of info about devices, so I use it and love it.
Maybe it is of some use to you to try it.
And Thank You for your explanation about /etc/config/rfd/, Just a bit hidden deep below.
cu
Harvey

**Comment by jp112sdl** [comment]
Mit dem HomeMatic-Manager kann man auch die Adressen sehen: https://github.com/hobbyquaker/homematic-manager

**Comment by harvey637** [comment]
Oh, ahh, schaue ich mir an - Danke!
