### ISSUE TITLE
No status in Homematic

### ISSUE THREAD

**Issue by williwacker** [jp112sdl/Beispiel_AskSinPP#2]
With this code I am not getting any status updates in the HM
`sdev.channel(1).init(SENS1_PIN,SENS1_PIN,SABOTAGE_PIN);`
After enabling the posmap and changing the code to:
`sdev.channel(1).init(SENS1_PIN,SENS1_PIN,posmap);`
 it sends the proper status to the  HM.
I just do not get any Sabotage messages.

**Comment by jp112sdl** [comment]
Which sketch did you use?

**Comment by williwacker** [comment]
HM-SEC-SC

**Comment by jp112sdl** [comment]
I have fixed it with ab04fd1
Please test... it worked for me.
