### ISSUE TITLE
Nano V3 with CH340

### ISSUE THREAD

**Issue by wIWa-grae** [jp112sdl/Beispiel_AskSinPP#24]
Hello, i try to use a Nano V3 mit CH340 and  a BME280 but the serial monitor shows T/H = 0/0.
Is there a chance to solve this. Whith th "Mini" it seems to work fine.

**Comment by jp112sdl** [comment]
Hi,

Sorry, I don't have a Nano so I can't give any support on it. 
Basically, the function should be the same as the Pro Mini.
But as I can see from the tech specs, the Nano works with 16MHz.
So the BOD fuse is set to 4.3V which is not useful for battery use.

Finally, I can only recommend to use an 8MHz Pro Mini.
