### ISSUE TITLE
Nach flashen keine Funktion.

### ISSUE THREAD

**Issue by Alveran81** [jp112sdl/Beispiel_AskSinPP#25]
Hallo,
nachdem ich einen funktionierenden HM-WDS40-TH-I-BME280 erfolgreich mehre Wochen getestet habe wollte ich ihn endlich in ein Gehäuse bauen und habe ihn durch eigenes verschulden zerstört (Kurzschluss)

Wollte sowieso drei neue Bauen aber ich habe jetzt hier drei Stück liegen mit dem gleichen Problem:
Arduino flasht erfolgreich ohne Fehlermeldung. Aber beim Anlernen blinkt auch die LED nicht(Anlernen funktioniert auch nicht.) 
Das einzige was im seriell Monitor von Arduino zu sehen ist das:
AskSin++ V3.1.1 (Dec 10 2018 10:16:17)

**Comment by jp112sdl** [comment]
Wenn gar nicht weiter kommt, könnte es am Sensor liegen.
Mehr fällt mir da auch nicht ein.

**Comment by Alveran81** [comment]
Du meinst am Temperatur Sensor? Kann man zum Testen auch ohne betreiben?

**Comment by jp112sdl** [comment]
> Du meinst am Temperatur Sensor?

Ja.

> Kann man zum Testen auch ohne betreiben?

Musst du ausprobieren.
Das sind so Sachen, die ich gewöhnlicher Weise nicht teste.

**Comment by Alveran81** [comment]
Hat sich erledigt. Fehler gefunden. Der Fehler saß natürlich wieder vor dem Lötkolben ;-)
