### ISSUE TITLE
Unterschied zwischen HM-RC-4 und HM-PBI-4-FM

### ISSUE THREAD

**Issue by Stuetti** [jp112sdl/Beispiel_AskSinPP#26]
Hallo,

ich nutze derzeit das [HM-RC-4](https://github.com/pa-pa/AskSinPP/blob/V3/examples/HM-RC-4/HM-RC-4.ino)-Sketch quasi für eine Tasterschnittstelle. Jetzt habe ich gesehen, dass du ein angepasstes Beispiel-Sketch [HM-PBI-4-FM](Beispiel_AskSinPP/examples/HM-PBI-4-FM/HM-PBI-4-FM.ino) in deinem Repository hast. 
Ich sehe, dass da der Hauptunterschied wahrscheinlich das Einbinden bzw. Weglassen der SPI.h (und damit _typedef AvrSPI_ anstatt _typedef LibSPI_) ist. Bringt das ggf. Vorteile bzgl. Performance und/oder Batterieverbrauch oder ist das vernachlässigbar?

Danke & Gruß
Stuetti

**Comment by jp112sdl** [comment]
Hi,

LibSPI nutzt die Hardware-SPI Pins, während man bei AvrSPI auch andere Pins verwenden könnte. Ein paar kleinere andere Differenzen gibts schon noch, aber nichts was sich jetzt hier auf die Schnelle erklären lässt.

> oder ist das vernachlässigbar?

Es ist letztlich zu vernachlässigen.

**Comment by Stuetti** [comment]
Okay, Danke.
