### ISSUE TITLE
HM-PB-MP-WM

### ISSUE THREAD

**Issue by eddy-ch** [jp112sdl/Beispiel_AskSinPP#28]
Hy Jerome
habe diesen super Sketch gefunden und ihn gleich eingesetzt, leider bleibt er nach unbestimmten Klicks hängen und nur ein reset hilft weiter. habe schon an den Zeiten gedreht, leider ohne Erfolg.

**Comment by jp112sdl** [comment]
Hi!
Das ist komisch... ich hatte sowas schon mal bei einem normalen Wandtaster.
Kannst du ungefähr abschätzen, wie häufig das vorkommt?

**Comment by eddy-ch** [comment]
Das ist sehr unterschiedlich, wenn ich es provozieren viel (viele tastendrücke hintereinander) nach ca. 10 -30 mal bleibt es manchmal hängen. meistens wenn die Frau Licht anmachen will und das ist es frustrierend.

**Comment by jp112sdl** [comment]
Also die gute Nachricht: Ich konnte es reproduzieren und auch bei mir tritt der Fehler nur sporadisch nach einem nicht nachvollziehbaren Muster auf.
Die schlechte: Ich konnte die Ursache noch nicht lokalisieren.
Jedoch habe ich eine Idee, die bei mir zumindest offensichtlich Besserung bringt.

Ändere in der `ButtonMP.h` bitte mal Zeile 29:
`#define DEBOUNCETIME millis2ticks(50)`
_(warum auch immer ich damals auf 30ms abgewichen bin...)_

und füge **nach** Zeile 102:
```
sysclock.cancel(ma);
```
ein.
Der Abschnitt sieht dann so aus:
```
...
      switch ( state() ) {
        case released:
          ma.set(millis2ticks(MULTIPRESSTIME));
          sysclock.cancel(ma);
          sysclock.add(ma);
        case longreleased:
...
```

**Comment by eddy-ch** [comment]
vielen Dank, werde es sofort testen und berichten.
habe übrigens beim entfernen von <LowPower.h> auch eine Besserung festgestellt, vlt. hilft es dir weiter.

**Comment by jp112sdl** [comment]
Das kann ich nahezu ausschließen, da die LowPower in der [Activity.h](https://github.com/pa-pa/AskSinPP/blob/350f2722829e90f45cb9763098094370ecff5dec/Activity.h#L14) so oder so gezogen wird.
Die Referenz im Sketch war eigentlich obsolet.

**Comment by eddy-ch** [comment]
habe es seit gestern ohne Aussetzer im Einsatz.
Denke das du es hinbekommen hasst.

**Comment by jp112sdl** [comment]
Danke für die Info!
Klingt echt gut... ich werds mal in den master-Code pushen.
