### ISSUE TITLE
Spannungsauswertung

### ISSUE THREAD

**Issue by quorle** [jp112sdl/Beispiel_AskSinPP#29]
Wenn man die origialen HM Geräte ansieht ( ich habe HM Thermostate ), wird die Spannung der Batterien mit übertragen. Ist die bei allen deinen Gerätesoftwares auch möglich?

**Comment by jp112sdl** [comment]
Hi,

Heizkörper- und Wandthermostat sind auch die einzigen beiden HM Geräte, die die Spannung als Wert übermitteln.

Bei allen HM-... Nachbauten hier in der Liste wird also nur das LOWBAT-Bit übermittelt, wie auch bei den originalen HM-Geräten.

Bei einigen meiner HB-... Eigenbauten gebe ich die Spannung als Wert mit.
z.B. beim [Füllstandsensor](https://github.com/jp112sdl/HB-UNI-Sen-LEV-US).

**Comment by quorle** [comment]
Das klingt wirklich super und dein Projekt gefällt mir. Könnte man die Spannungsübermittlung nicht überall mit einbauen?

**Comment by jp112sdl** [comment]
Nein, das geht nicht, zumindest nicht bei den Orignalgeräten / -nachbauten.

**Comment by quorle** [comment]
Könntest du mir mitteilen, ab wann das LOWBAT-Bit gesetzt wird? Hier muss es ja eine definierte Spannungsschwelle geben. 

Noch kurz am Rande, wie ermittelt man eine Seriennummer und wandelt diese in Hexadezimal um?

Schon einmal wirklich besten Dank für das Projekt und deine Hilfestellungen.

**Comment by jp112sdl** [comment]
> Könntest du mir mitteilen, ab wann das LOWBAT-Bit gesetzt wird? Hier muss es ja eine definierte Spannungsschwelle geben.

Das ist in den Sketchen mit `battery.low()` definiert, siehe z.B. [hier](https://github.com/jp112sdl/Beispiel_AskSinPP/blob/master/examples/HM-WDS40-TH-I-SHT10/HM-WDS40-TH-I-SHT10.ino#L71).

`22` bedeutet 2,2V.



> Noch kurz am Rande, wie ermittelt man eine Seriennummer und wandelt diese in Hexadezimal um?

Viele Informationen zum Thema AskSinPP findest du auch in der [AskSinPPCollection](https://jp112sdl.github.io/AskSinPPCollection/).

Du musst die Seriennummer nicht umwandeln. Die "Device Serial" ist 10 Zeichen plain text, so wie sie dann auch in der WebUI angezeigt wird.
Die "Device ID" - also die Adresse - ist unabhängig davon aus 3 Bytes HEX bestehend.

Mehr dazu findest du in der AskSinPPCollection unter  [Sketch anpassen und flashen](https://jp112sdl.github.io/AskSinPPCollection/Grundlagen/02_software.html#sketch-anpassen-und-flashen).
