### ISSUE TITLE
CC1101 Fritzing Bauteil

### ISSUE THREAD

**Issue by nohum** [jp112sdl/Beispiel_AskSinPP#31]
Hallo!

Woher hast du denn das Fritzing-Bauteil für den CC1101? Ich würde das fürs eigene Prototyping bzw. dann PCB-Export suchen, hab das aber leider nirgends bisher gefunden.

**Comment by jp112sdl** [comment]
Hi!
Das ist eine sehr gute Frage... ich weiß es gar nicht mehr. Ich weiß auch nicht ob die Dimensionen stimmen

**Comment by nohum** [comment]
Hm okay. Könntest du mir bitte das Fritzing Part-File dennoch mal hier anhängen?

**Comment by jp112sdl** [comment]
Schau mal hier: https://bitbucket.org/SciBee/hb-uni-sen-res-moist/src/master/Fritzing/

**Comment by nohum** [comment]
Danke!
