### ISSUE TITLE
HM-WDS40-TH-I-SI7021 built issue

### ISSUE THREAD

**Issue by fraeggle** [jp112sdl/Beispiel_AskSinPP#34]
Hallo.
Ich versuche verzweifelt HM-WDS40-TH-I-SI7021 zu kompilieren. Ich verwende Atom, habe die Asksinpp Bibliothek installiert.
![grafik](https://user-images.githubusercontent.com/40692505/68889764-d52a8100-071d-11ea-9aa9-7b3212fe7136.png)
ich bekomme aber immer folgenden Fehler:
C:\users\reinisch\.platformio\lib\AskSinPP-master/sensors/Si7021.h:23:46: error: 'class SI7021' has no member named 'getDeviceID'
     if (_si7021.getDeviceID() > 0 && _si7021.getDeviceID() != 255) {
                                              ^
C:\users\reinisch\.platformio\lib\AskSinPP-master/sensors/Si7021.h: In member function 'bool as::Si7021::measure(bool)'
:
C:\users\reinisch\.platformio\lib\AskSinPP-master/sensors/Si7021.h:34:30: error: 'class SI7021' has no member named 'readTemp'
       _temperature = _si7021.readTemp() * 10;
                              ^
C:\users\reinisch\.platformio\lib\AskSinPP-master/sensors/Si7021.h:35:27: error: 'class SI7021' has no member named 'readHumidity'
       _humidity = _si7021.readHumidity();
                           ^
*** [.pio\build\pro8MHzatmega328\src\HM-WDS40-TH-I-SI7021.ino.cpp.o] Error 1

Was mach ich falsch?

**Comment by jp112sdl** [comment]
Hmm, zu Atom kann ich leider nix sagen.

Die [Si7021 Lib](https://github.com/jp112sdl/Beispiel_AskSinPP/blob/85c47756df8f4658ac97889a274d686d3a4648b8/examples/HM-WDS40-TH-I-SI7021/HM-WDS40-TH-I-SI7021.ino#L16) hast du installiert?
https://github.com/jayjayuk/Si7021-Humidity-And-Temperature-Sensor-Library

In Sloeber und Arduino IDE kompiliert es ohne Probleme.

**Comment by fraeggle** [comment]
hi Jerome. Nachdem ich gestern um 23 uhr genau diese LIB dann ins LIB Verzeichnis des Sketches rein hab, gings..   Also denk ich ganz stark an PEBCAK  Problem exists between chair and keyboard  ;-)

Gruß Peter
