### ISSUE TITLE
HM-SWI-3-FM in Raspberrymatic nur mit "Betätigt"

### ISSUE THREAD

**Issue by diddi68** [jp112sdl/Beispiel_AskSinPP#39]
Hallo JP,

ich habe mir mal den HM-SWI-3-FM nachgebaut und in der RM angemeldet. Funktioniert soweit alles, nur gibt es in der WebUI lediglich den Status "Betätigt" (sowohl in "Status und Bedienung > Geräte" wie auch in den Programmen). Ich kann daher nur eine Aktion starten, wenn der Schalter geschlossen, jedoch nicht, wenn er geöffnet ist. Beim Durchsuchen des Addon-Verzeichnisses ist auch kein Device "HM-SWI-3-FM" o.ä. auffindbar.

Trotzdem großes Kompliment für diese Arbeit.

**Comment by jp112sdl** [comment]
Hi,

du verwechselst nicht zufällig den HM-S**W**I-3-FM mit dem HM-S**C**I-3-FM?

Allgemein gilt auch: Gesicherte Übertragung auf Standard umgestellt?
https://asksinpp.de/Grundlagen/FAQ/Standard_vs_gesicherte_Uebertragung.html

> Beim Durchsuchen des Addon-Verzeichnisses ist auch kein Device "HM-SWI-3-FM" o.ä. auffindbar.

Das Addon ist nur für eigene Gerätetypen notwendig, die die CCU nicht kennt.
Also alles was mit **HB**-... anfängt.

**Comment by diddi68** [comment]
Ja, Übertragung ist auf "Standard" gesetzt.  Hier mal ein Bild der Gerätesteuerung:
![Geraete](https://user-images.githubusercontent.com/69699942/94905032-7fc5a280-049c-11eb-8692-d8e668ac8e55.png)
In der Bedienungsanleitung des HM-SWI-3-FM steht "Die drei Kanäle werden im Auslieferungszustand als drei Ein-/Aus-Schalter (AN/AUS) am Empfänger angelernt. Schaltaktoren können dann AN/AUS geschaltet werden. Jalousieaktoren fahren herauf bzw.
herunter (AUF/STOPP/AB/STOPP). Auch Wechselschaltungen können mit der Schalterschnittstelle realisiert werden."

Verstehe ich da was falsch?

**Comment by jp112sdl** [comment]
Der SWI-3 sollte sich so verhalten:
Kontakt wird geschlossen > kurzer Tastendruck wird gesendet
Kontakt wird geöffnet > kurzer Tastendruck wird gesendet

Passiert das? Im seriellen Monitor sollte auch jedes Mal erkennbar sein, dass ein Telegramm gesendet wird.

Wie das nachher in den Direktverknüpfungen aussehen muss, um das von dir erwartete Verhalten abzubilden, kann ich dir leider nicht sagen, da ich keinen SWI-3 verwende.

**Comment by diddi68** [comment]
Ja, er sendet beim Schließen und beim Öffnen. In der Raspi gibt es jedoch nur einen Zustand: "Betätigt", d.h. ich kann in Programmen nur auswerten, ob geschaltet wird, nicht aber ob "ein" oder "aus". Damit kann ich keinen Schalter realisieren. Ich habe leider auch keinen Originalen SWI-3 um es zu vergleichen. Ich werd mal den HM-Sec-SC ausprobieren, da mir ein Kanal genügt. Trotzdem vielen Dank für Deine Hilfe.

**Comment by jp112sdl** [comment]
>  In der Raspi gibt es jedoch nur einen Zustand: "Betätigt" 

Ja, dann ist das korrekt so.

> Damit kann ich keinen Schalter realisieren

Siehe auch ELV:
https://de.elv.com/homematic-3fach-funk-schalterschnittstelle-unterputzmontage-hm-swi-3-fm-fuer-smart-home-hausautomation-076785?fs=861234933

> Hinweis: Für die Zustandsauswertung von Schaltkontakten ist dieses Modul nicht geeignet, hierzu bitte folgendes Produkt wählen:
> Homematic Schließerkontakt-Interface für Öffner und Schließerkontakte; Artikel-Nummer: 68-09 20 68

Wenn du den tatsächlichen Zustand (Schalter EIN, Schalter AUS) erfassen willst, brauchst du einen HM-S**C**I-3-FM

**Comment by diddi68** [comment]
Vielen Dank, das war mir so nicht bewußt bzw. hab ich das ganz anders interpretiert.
