### ISSUE TITLE
Frage zu Sonoff POW R2

### ISSUE THREAD

**Issue by fraeggle** [jp112sdl/Beispiel_AskSinPP#41]
Hallo. Ich habe eine Frage zum Umbau des Sonoff POW R2. Den ich hier habe, hat ein anderes Layout als das Beispiel im Sketch.
Ausserdem verwendet er den CSE7759. Dieser hat kein SEL und verwendet statt CF und CF1  nur den "TI".
Was muss im Sketch angepasst werden? Und vor allem hab ich das Problem, das ich die nötigen Pins nicht weiß.
Vielleicht hat einer schon einen auf HM umgebaut?

![20201205_173328](https://user-images.githubusercontent.com/40692505/101260082-80ddaf00-372d-11eb-9357-6fae133be2ce.jpg)

Gruss Peter

**Comment by jp112sdl** [comment]
Hi, 
der POW R2 funktioniert komplett anders als der "alte" POW.

Der CSE7759 arbeitet seriell... da ist nix mit "schnell mal was im Sketch anpassen"

**Comment by jp112sdl** [comment]
Aber du kannst deine Frage sonst am besten mal im HM Forum stellen... da lesen mehr Leute mit

**Comment by fraeggle** [comment]
hi.
1 Functional Description of the Chip
CSE7759B is a single-phase multi-function measuring chip, provides high-frequency pulse
CF for measuring electric quantity and may read relevant parameters of current, voltage and
power (such as coefficient, cycle) directly through UART; baud rate of serial port is 4800bps
(± 2%) 8-bit data with 1 even parity check and 1 stop bit. This chip is packaged in SOP8
Hmm ich glaub Entscheidend ist das "B" dass ich vergessen hab mit an zugeben.
Es ist auch so dass wirklich nur Pin 6 auf de Platine verwendet wird. Pin7 wird nicht verwendet. Deswegen wird das Srcipt wahrscheinlich leider nicht gehen (da UART). Ich werd mal im HM Forum fragen.
Würde aufgrund der WLan Situation im Keller lieber HM nehmen. Da hab ich schon mehrere deiner "Nachbauten"...
Danke dir.

![cse7759_1](https://user-images.githubusercontent.com/40692505/101275281-b7a2dc00-37a4-11eb-9485-4988256cdacd.PNG)
Gruß Peter

**Comment by fraeggle** [comment]
Hab mal im HM nachgefragt.... mal sehn..........

**Comment by jp112sdl** [comment]
Alles klar, das **B** macht den Unterschied.

Ja, mal schauen was das Forum sagt.

Ich selbst habe keinen POW R2
