### ISSUE TITLE
Problem mit HM-LC-Sw1-Pl-DN-R1_OBI

### ISSUE THREAD

**Issue by fraeggle** [jp112sdl/Beispiel_AskSinPP#42]
Ich versteh das nicht.
Ich verwende HM-LC-Sw1-Pl-DN-R1_OBI.ino. Hab nur die Device ID und Device Serial angepasst. Nun hab ich folgendes Problem.
Zum einen sagt das Relais UND die LED das Gerät ist aus, in der CCU steht es als  AN  und umgekehrt.
Wenn der Stecker strom bekommt, Schaltet er sich immer EIN, steht dann in der CCU natürlich als aus.
Ich verstehs nicht wirklich.
Hab den auch schon über gaaanz lang drücken auf Werksreset gestellt und auch in der CCU neu angelernt.

Ein anderer (war der erste ) funktioniert, wie er soll.

**Comment by jp112sdl** [comment]
War das bei dem OBI Ding nicht so, dass das Relais nur kurz getastet wird zum Toggeln?

**Comment by fraeggle** [comment]
das ist möglich, aber wie gesagt, stimmt der Zustand vom Relais und LED überein, Nur sagt die CCU das genaue gegenteil, umd beim Reset oder Neustart schaltet sich der sofort ein. Was in der CCU dann als "AUS" steht, aber LED und Relais sind EIN.
ich versteh nicht. wieso der erst funktioniert, wie er soll und der zweite das genaue gegenteil macht.

**Comment by fraeggle** [comment]
einziger Unterschied den ich im Moment seh:
Dieser Funktioniert wie er soll
AskSin++ V4.1.7 (Nov  6 2020 09:43:25)
Address Space: 32 - 256
CC init1
CC Version: 14
dieser nicht:

AskSin++ V4.1.7 (Feb  1 2021 07:40:25)
Address Space: 32 - 256
CC init1
CC Version: 04
aber ich schätze mal das ist nur der Zeitstempel des "erstell Datums" der Hex.

**Comment by jp112sdl** [comment]
Ja und das Funkmodul antwortet anders 14 vs. 04

Dass das aber was mit dem Schaltzustand zu tun haben soll, schließe ich eigentlich aus

**Comment by fraeggle** [comment]
OMG
 Ich Vollhorst.......  Schande.............. Wenn du Rls on und off Falsch bezeichnet und somit vertauscht hast........kommt sowas dabei raus. 2 mal nachgeschaut.

Kabel getauscht und nun tut es.

Danke für deine Sketche.. 

Gruß Peter
