### ISSUE TITLE
Frage zu GAS_POWER

### ISSUE THREAD

**Issue by JurgenO** [jp112sdl/Beispiel_AskSinPP#46]
Hallo,

gibt es eine Definition des Parameters GAS_POWER so wie er in der HM-ES-TX-WM verwendet wird ?

Sollte es der "Gasverbrauch in einer Minute sein", dann berechnet das HM-ES-TX-WM Beispiel [an dieser Stelle](https://github.com/jp112sdl/Beispiel_AskSinPP/blob/069665f824a6b4a29d2ee0de67a5a19fa46ff1c3/examples/HM-ES-TX-WM_CCU/HM-ES-TX-WM_CCU.ino#L352)  die _actualConsumption_:

` actualConsumption = (c * sigs * 10) / (MSG_CYCLE / seconds2ticks(60));`
oder 
` actualConsumption = (c * sigs * 10) / 3`

Das heisst, bei einem Impuls (c=1) und bei einer Konfiguration von 0.01m3 / Impuls ist
` actualConsumption = (1 * 10 * 10) / 3 = 33.3`

In der Homematic wird das dann als 0,03 m3 angezeigt.

Tatsächlich aber ist der Verbrauch

1 Impuls = 0.01 m3 / 3 min = 0.0033 m3/ min

Gruss
Juergen

**Comment by jp112sdl** [comment]
Puh ,ich steck da nicht im Thema. 

Wenn du die Formel selbst korrigieren kannst, mach mir gern einen PullRequest

**Comment by JurgenO** [comment]
Danke für die schnelle Antwort.
Sobald ich weiss welchen Wert der eq3 Gassensor für GAS_POWER anzeigt werde ich einen pull request öffnen.
Ich schließe den Issue hier und stelle die Frage im Homematic Forum.

Gruß
Jürgen

**Comment by JurgenO** [comment]
Issue closed

**Comment by JurgenO** [comment]
Closed
