### ISSUE TITLE
HM-Dis-WM55

### ISSUE THREAD

**Issue by chianti2000** [jp112sdl/Beispiel_AskSinPP#50]
Möchte das Display mit dem 1284P nachbauen. 
Ist die Belegung in der .ino STD oder Bobuino?

**Comment by jp112sdl** [comment]
Hi, _müsste_ Bobuino sein.
Der Sketch ist 5 Jahre alt... ich hab da keinen Plan mehr von 😄

**Comment by jp112sdl** [comment]
Was meinst du mit "Selbstbauvariante für so ein kleines Display?"

2 Varianten hast du ja bereits erwähnt... HB-RC-4-Dis-TH und hier das HM-Dis-WM55
