### ISSUE TITLE
HM-SEN-LI-O

### ISSUE THREAD

**Issue by lukashauck89** [jp112sdl/Beispiel_AskSinPP#8]
Mal eine Fragee zum Helligkeitssensor er funktioniert an sich gut. Zwischen 7 un 9 Uhr Morgens steigt er aus und sendet nichts mehr und gegen 16 - 18 Uhr sendet er wieder Daten dazwischen immer keine Datenübertragung.
Ich habe auch noch nicht ganz gerafft wie ich die Aktualisierungsrate ändern kann wenn er läuft sendet er fast alle Sekunde neue Daten.

**Comment by jp112sdl** [comment]
Bist du dir sicher, dass du einen 3.3V __8MHz__ Pro Mini hast?

Die Aktualisierungsrate stellst du in der WebUI in den Geräteeinstellungen ein.

**Comment by jp112sdl** [comment]
Gibts hier was Neues oder kann der Issue zu?

**Comment by lukashauck89** [comment]
Sorry,
war im Urlaub hab keine E-mails gelesen. Also das mit der Aktualisierungsrate hab ich jetzt mal auf 120 Sekunden gesetzt das reicht mir für meine zwecke. Aber das er Tagsüber keine Werte liefert ist immer noch so heute letzte Übertragung 8:21 Uhr seit dem nichts mehr.

**Comment by lukashauck89** [comment]
Hab gestern Abend mal die Protokollierung aktiviert. Vielleicht hat der TSL2561 ein Lux-Grenze, also zu hell. Mal schauen.

**Comment by jp112sdl** [comment]
Ja, hat er. Mit dem TSL2561 habe ich nur schlechte Erfahrungen gemacht.
Ich setze grundsätzlich nur den BH1750 ein, bzw. werde demnächst mal den MAX44009 testen.
Aber der TSL2561 ist grütze.

**Comment by lukashauck89** [comment]
Hatte noch einen rumfliegen, aber habe glaube auch noch einen BH 1750. werde ich mal testen.
